name: ISO

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    steps:
      - name: Restore pacman cache
        uses: actions/cache@v3
        with:
          path: /var/cache/pacman/pkg
          key: pacman-cache-${{ github.workflow }}-build

      - name: Install dependencies
        run: pacman -Syyu --needed --noconfirm archiso

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ISO
        run: mkarchiso -v -o ./out ./config

      - name: Upload ISO
        uses: actions/upload-artifact@v3
        with:
          name: iso-files
          path: ./out/*.iso
