name: ISO

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: "Create a release"
        type: boolean
        default: false
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
      options: --privileged
    steps:
      - name: Restore pacman cache
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: pacman-cache-${{ github.workflow }}-build

      - name: Install dependencies
        run: pacman -Syyu --needed --noconfirm archiso git

      - name: Checkout
        uses: actions/checkout@v4

      - name: Apply patches
        run: ./scripts/apply-patches.sh

      - name: Build ISO
        run: mkarchiso -v -o ./out ./releng

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: iso-files
          path: ./out/*.iso

  relase:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'schedule' || github.event.inputs.release
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download ISO
        uses: actions/download-artifact@v4
        with:
          name: iso-files
          path: ./out

      - name: Generate Release Info
        id: release-info
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.0
        with:
          files: ./out/*.iso
          name: ${{ steps.release-info.outputs.date }}
          tag_name: ${{ steps.release-info.outputs.date }}
          draft: ${{ github.event_name != 'schedule' }}
